language: python
dist: xenial
python:
  - "2.7"
  - "3.4"
  - "3.6"
  - "3.7"
  - "3.9"
  - "3.10"

addons:
  apt:
    packages:
      - libpcap-dev

install:
  - pip install tox-travis

script:
  - tox -v

notifications:
  email:
    on_success: never
    on_failure: always

webhooks:
  urls:
  on_success: change  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
